# Example configuration file, anything in <> needs to be replaced

human_interface:
    name: slack
    bot_name: <bot user name>
    bot_user_token: <bot-token>
    channel: <channel bot listens to>

security_interface:
    name: zoneminder
    url: <protocol>://<ip_address>:<port>/zm
    username: <username>
    password: <password>

users:
    - 'slack:<slack_user_id>:<common_name>'

permissions:
    # You can provide '*' as the command or option to make it match anything the user types
    - 'zoneminder:<common_name>:<command>:<option>'